// Code generated by protoc-gen-go.
// source: pb_common.proto
// DO NOT EDIT!

/*
Package pb_common is a generated protocol buffer package.

It is generated from these files:
	pb_common.proto

It has these top-level messages:
	UserT
	EventT
	ItemT
*/
package pb_common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ////////////////////////////////////////////
// 错误码
// ////////////////////////////////////////////
type E_ERROR_CODE int32

const (
	E_ERROR_CODE_ERROR_SMS_SENDING       E_ERROR_CODE = 10000
	E_ERROR_CODE_ERROR_SMS_REGISTER_CODE E_ERROR_CODE = 10001
	E_ERROR_CODE_ERROR_USER_EXIST        E_ERROR_CODE = 10002
	E_ERROR_CODE_ERROR_PHONE_NUM_BIND    E_ERROR_CODE = 10003
	E_ERROR_CODE_ERROR_PHONE_NUM_NO_BIND E_ERROR_CODE = 10004
)

var E_ERROR_CODE_name = map[int32]string{
	10000: "ERROR_SMS_SENDING",
	10001: "ERROR_SMS_REGISTER_CODE",
	10002: "ERROR_USER_EXIST",
	10003: "ERROR_PHONE_NUM_BIND",
	10004: "ERROR_PHONE_NUM_NO_BIND",
}
var E_ERROR_CODE_value = map[string]int32{
	"ERROR_SMS_SENDING":       10000,
	"ERROR_SMS_REGISTER_CODE": 10001,
	"ERROR_USER_EXIST":        10002,
	"ERROR_PHONE_NUM_BIND":    10003,
	"ERROR_PHONE_NUM_NO_BIND": 10004,
}

func (x E_ERROR_CODE) Enum() *E_ERROR_CODE {
	p := new(E_ERROR_CODE)
	*p = x
	return p
}
func (x E_ERROR_CODE) String() string {
	return proto.EnumName(E_ERROR_CODE_name, int32(x))
}
func (x *E_ERROR_CODE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(E_ERROR_CODE_value, data, "E_ERROR_CODE")
	if err != nil {
		return err
	}
	*x = E_ERROR_CODE(value)
	return nil
}

// 用户事件
type USER_EVENT_TYPE int32

const (
	// ----------------------------------------------------------------------------
	// 每日事件 DAILY_EVENT_XX
	USER_EVENT_TYPE_DAILY_EVENT_BEGIN USER_EVENT_TYPE = 100000
	USER_EVENT_TYPE_DAILY_EVENT_END   USER_EVENT_TYPE = 199999
	// ----------------------------------------------------------------------------
	// 每周事件 WEEKLY_EVENT_XX
	USER_EVENT_TYPE_WEEKLY_EVENT_BEGIN USER_EVENT_TYPE = 200000
	USER_EVENT_TYPE_WEEKLY_EVENT_END   USER_EVENT_TYPE = 299999
	// ----------------------------------------------------------------------------
	// 每月事件 MONTHLY_EVENT_XX
	USER_EVENT_TYPE_MONTHLY_EVENT_BEGIN USER_EVENT_TYPE = 300000
	USER_EVENT_TYPE_MONTHLY_EVENT_END   USER_EVENT_TYPE = 399999
	// ----------------------------------------------------------------------------
	// 永久事件 FOREVER_EVENT_XX
	USER_EVENT_TYPE_FOREVER_EVENT_BEGIN USER_EVENT_TYPE = 400000
	USER_EVENT_TYPE_FOREVER_EVENT_END   USER_EVENT_TYPE = 499999
	// ----------------------------------------------------------------------------
	// 过期事件 EXPRIE_EVENT_XX
	USER_EVENT_TYPE_EXPRIE_EVENT_BEGIN USER_EVENT_TYPE = 500000
	USER_EVENT_TYPE_EXPRIE_EVENT_END   USER_EVENT_TYPE = 599999
)

var USER_EVENT_TYPE_name = map[int32]string{
	100000: "DAILY_EVENT_BEGIN",
	199999: "DAILY_EVENT_END",
	200000: "WEEKLY_EVENT_BEGIN",
	299999: "WEEKLY_EVENT_END",
	300000: "MONTHLY_EVENT_BEGIN",
	399999: "MONTHLY_EVENT_END",
	400000: "FOREVER_EVENT_BEGIN",
	499999: "FOREVER_EVENT_END",
	500000: "EXPRIE_EVENT_BEGIN",
	599999: "EXPRIE_EVENT_END",
}
var USER_EVENT_TYPE_value = map[string]int32{
	"DAILY_EVENT_BEGIN":   100000,
	"DAILY_EVENT_END":     199999,
	"WEEKLY_EVENT_BEGIN":  200000,
	"WEEKLY_EVENT_END":    299999,
	"MONTHLY_EVENT_BEGIN": 300000,
	"MONTHLY_EVENT_END":   399999,
	"FOREVER_EVENT_BEGIN": 400000,
	"FOREVER_EVENT_END":   499999,
	"EXPRIE_EVENT_BEGIN":  500000,
	"EXPRIE_EVENT_END":    599999,
}

func (x USER_EVENT_TYPE) Enum() *USER_EVENT_TYPE {
	p := new(USER_EVENT_TYPE)
	*p = x
	return p
}
func (x USER_EVENT_TYPE) String() string {
	return proto.EnumName(USER_EVENT_TYPE_name, int32(x))
}
func (x *USER_EVENT_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(USER_EVENT_TYPE_value, data, "USER_EVENT_TYPE")
	if err != nil {
		return err
	}
	*x = USER_EVENT_TYPE(value)
	return nil
}

// //////////////////////////////////////////////////
// 结构体
// //////////////////////////////////////////////////
// 用户数据
type UserT struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Nick             *string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserT) Reset()         { *m = UserT{} }
func (m *UserT) String() string { return proto.CompactTextString(m) }
func (*UserT) ProtoMessage()    {}

func (m *UserT) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UserT) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

// 事件
type EventT struct {
	Type             *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Id               *uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Data             *uint32 `protobuf:"varint,3,opt,name=data" json:"data,omitempty"`
	Time             *uint32 `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	StrData          *string `protobuf:"bytes,5,opt,name=strData" json:"strData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EventT) Reset()         { *m = EventT{} }
func (m *EventT) String() string { return proto.CompactTextString(m) }
func (*EventT) ProtoMessage()    {}

func (m *EventT) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *EventT) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *EventT) GetData() uint32 {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return 0
}

func (m *EventT) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *EventT) GetStrData() string {
	if m != nil && m.StrData != nil {
		return *m.StrData
	}
	return ""
}

// //////////////////////////////////////////////////
// 道具
// //////////////////////////////////////////////////
type ItemT struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Cnt              *uint32 `protobuf:"varint,3,opt,name=cnt" json:"cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemT) Reset()         { *m = ItemT{} }
func (m *ItemT) String() string { return proto.CompactTextString(m) }
func (*ItemT) ProtoMessage()    {}

func (m *ItemT) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ItemT) GetCnt() uint32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

func init() {
	proto.RegisterType((*UserT)(nil), "pb_common.user_t")
	proto.RegisterType((*EventT)(nil), "pb_common.event_t")
	proto.RegisterType((*ItemT)(nil), "pb_common.item_t")
	proto.RegisterEnum("pb_common.E_ERROR_CODE", E_ERROR_CODE_name, E_ERROR_CODE_value)
	proto.RegisterEnum("pb_common.USER_EVENT_TYPE", USER_EVENT_TYPE_name, USER_EVENT_TYPE_value)
}
