// Code generated by protoc-gen-go.
// source: pb_square.proto
// DO NOT EDIT!

/*
Package pb_square is a generated protocol buffer package.

It is generated from these files:
	pb_square.proto

It has these top-level messages:
	LoginMsg
	LoginMsgRes
	SysTimeMsg
	SysTimeMsgRes
*/
package pb_square

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginMsg struct {
	Account          *string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}

func (m *LoginMsg) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginMsg) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type LoginMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginMsgRes) Reset()         { *m = LoginMsgRes{} }
func (m *LoginMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoginMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 系统
// //////////////////////////////////////////////
type SysTimeMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SysTimeMsg) Reset()         { *m = SysTimeMsg{} }
func (m *SysTimeMsg) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsg) ProtoMessage()    {}

type SysTimeMsgRes struct {
	TimeSecond       *uint32 `protobuf:"varint,1,opt,name=TimeSecond" json:"TimeSecond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SysTimeMsgRes) Reset()         { *m = SysTimeMsgRes{} }
func (m *SysTimeMsgRes) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsgRes) ProtoMessage()    {}

func (m *SysTimeMsgRes) GetTimeSecond() uint32 {
	if m != nil && m.TimeSecond != nil {
		return *m.TimeSecond
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginMsg)(nil), "pb_square.LoginMsg")
	proto.RegisterType((*LoginMsgRes)(nil), "pb_square.LoginMsgRes")
	proto.RegisterType((*SysTimeMsg)(nil), "pb_square.SysTimeMsg")
	proto.RegisterType((*SysTimeMsgRes)(nil), "pb_square.SysTimeMsgRes")
}
