// Code generated by protoc-gen-go.
// source: pb_square.proto
// DO NOT EDIT!

/*
Package pb_square is a generated protocol buffer package.

It is generated from these files:
	pb_square.proto

It has these top-level messages:
	LoginMsg
	LoginMsgRes
	CreateRoleMsg
	CreateRoleMsgRes
	LoadUserMsg
	LoadUserMsgRes
	SysTimeMsg
	SysTimeMsgRes
*/
package pb_square

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pb_common "pb_common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginMsg struct {
	Platform          *uint32 `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	Account           *string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Password          *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	WechatAccessToken *string `protobuf:"bytes,100,opt,name=wechat_access_token" json:"wechat_access_token,omitempty"`
	WechatOpenid      *string `protobuf:"bytes,101,opt,name=wechat_openid" json:"wechat_openid,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}

func (m *LoginMsg) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *LoginMsg) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginMsg) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginMsg) GetWechatAccessToken() string {
	if m != nil && m.WechatAccessToken != nil {
		return *m.WechatAccessToken
	}
	return ""
}

func (m *LoginMsg) GetWechatOpenid() string {
	if m != nil && m.WechatOpenid != nil {
		return *m.WechatOpenid
	}
	return ""
}

type LoginMsgRes struct {
	HasRole          *uint32 `protobuf:"varint,1,opt,name=has_role" json:"has_role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsgRes) Reset()         { *m = LoginMsgRes{} }
func (m *LoginMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoginMsgRes) ProtoMessage()    {}

func (m *LoginMsgRes) GetHasRole() uint32 {
	if m != nil && m.HasRole != nil {
		return *m.HasRole
	}
	return 0
}

type CreateRoleMsg struct {
	Nick             *string `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoleMsg) Reset()         { *m = CreateRoleMsg{} }
func (m *CreateRoleMsg) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsg) ProtoMessage()    {}

func (m *CreateRoleMsg) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

type CreateRoleMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoleMsgRes) Reset()         { *m = CreateRoleMsgRes{} }
func (m *CreateRoleMsgRes) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsgRes) ProtoMessage()    {}

type LoadUserMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoadUserMsg) Reset()         { *m = LoadUserMsg{} }
func (m *LoadUserMsg) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsg) ProtoMessage()    {}

type LoadUserMsgRes struct {
	User             *pb_common.UserT    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Events           []*pb_common.EventT `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *LoadUserMsgRes) Reset()         { *m = LoadUserMsgRes{} }
func (m *LoadUserMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsgRes) ProtoMessage()    {}

func (m *LoadUserMsgRes) GetUser() *pb_common.UserT {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoadUserMsgRes) GetEvents() []*pb_common.EventT {
	if m != nil {
		return m.Events
	}
	return nil
}

// //////////////////////////////////////////////
// 系统
// //////////////////////////////////////////////
type SysTimeMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SysTimeMsg) Reset()         { *m = SysTimeMsg{} }
func (m *SysTimeMsg) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsg) ProtoMessage()    {}

type SysTimeMsgRes struct {
	TimeSecond       *uint32 `protobuf:"varint,1,opt,name=TimeSecond" json:"TimeSecond,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SysTimeMsgRes) Reset()         { *m = SysTimeMsgRes{} }
func (m *SysTimeMsgRes) String() string { return proto.CompactTextString(m) }
func (*SysTimeMsgRes) ProtoMessage()    {}

func (m *SysTimeMsgRes) GetTimeSecond() uint32 {
	if m != nil && m.TimeSecond != nil {
		return *m.TimeSecond
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginMsg)(nil), "pb_square.login_msg")
	proto.RegisterType((*LoginMsgRes)(nil), "pb_square.login_msg_res")
	proto.RegisterType((*CreateRoleMsg)(nil), "pb_square.create_role_msg")
	proto.RegisterType((*CreateRoleMsgRes)(nil), "pb_square.create_role_msg_res")
	proto.RegisterType((*LoadUserMsg)(nil), "pb_square.load_user_msg")
	proto.RegisterType((*LoadUserMsgRes)(nil), "pb_square.load_user_msg_res")
	proto.RegisterType((*SysTimeMsg)(nil), "pb_square.SysTimeMsg")
	proto.RegisterType((*SysTimeMsgRes)(nil), "pb_square.SysTimeMsgRes")
}
