// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

/*
Package game_msg is a generated protocol buffer package.

It is generated from these files:
	game.proto

It has these top-level messages:
	ErrMsgRes
	LoginMsg
	LoginMsgRes
	CreateRoleMsg
	CreateRoleMsgRes
	LoadUserMsg
	LoadUserMsgRes
	LoginMsgEnd
	InMapMsg
	InMapMsgRes
	NotifyInMapMsgRes
	NotifyOutMapMsgRes
	MapWalkMsg
	MapWalkMsgRes
	NotifyMapWalkMsgRes
	NotifyMapChangeMsgRes
	GetPrivateMapPosMsg
	GetPrivateMapPosMsgRes
	GetMapDataMsg
	GetMapDataMsgRes
	OccupyResourcePosMsg
	OccupyResourcePosMsgRes
	GetResourcePosMsg
	GetResourcePosMsgRes
	UpdateResourceLineupMsg
	UpdateResourceLineupMsgRes
	GetPrivateMapItemPosMsg
	GetPrivateMapItemPosMsgRes
	OpenFairylandMsg
	OpenFairylandMsgRes
	GetBtlSceneMsg
	GetBtlSceneMsgRes
	UpdateFairylandLineupMsg
	UpdateFairylandLineupMsgRes
	GetOfflineUserPrivateMapMsg
	GetOfflineUserPrivateMapMsgRes
	NotifyKickOutMapMsg
	NotifyKickOutMapMsgRes
	NotifyPrivateMapBtlMsg
	NotifyPrivateMapBtlMsgRes
	PrivateMapBagMsg
	PrivateMapBagMsgRes
	ChatMsg
	ChatMsgRes
	NotifyChatMsgRes
	OnMountMsg
	OnMountMsgRes
	OffMountMsg
	OffMountMsgRes
	AcceptTaskMsg
	AcceptTaskMsgRes
	FinishTaskMsg
	FinishTaskMsgRes
	RewardTaskMsg
	RewardTaskMsgRes
	UpdateEventMsg
	UpdateEventMsgRes
	MailReadMsg
	MailReadMsgRes
	MailDelMsg
	MailDelMsgRes
	MailAttachmentMsg
	MailAttachmentMsgRes
	NotifyMailMsg
	NotifyMailMsgRes
	BtlServerOfflineMsg
	BtlServerOfflineMsgRes
	BtlPrivateMapInMsg
	BtlPrivateMapInMsgRes
	BtlPrivateOutMsg
	BtlPrivateOutMsgRes
	BtlPrivateMapFairylandInMsg
	BtlPrivateMapFairylandInMsgRes
	BtlPrivateMapFairylandOutMsg
	BtlPrivateMapFairylandOutMsgRes
	BtlPrivateMapPeerInMsg
	BtlPrivateMapPeerInMsgRes
	BtlPrivateMapPeerOutMsg
	BtlPrivateMapPeerOutMsgRes
	BtlPrivateMapPeerResourcesInMsg
	BtlPrivateMapPeerResourcesInMsgRes
	BtlPrivateMapPeerResourcesOutMsg
	BtlPrivateMapPeerResourcesOutMsgRes
	BtlPrivateMapPeerDuelOutMsg
	BtlPrivateMapPeerDuelOutMsgRes
	NotifyItemMsg
	NotifyItemMsgRes
	GetForageItemMsg
	GetForageItemMsgRes
	EquipmentDelMsg
	EquipmentDelMsgRes
	NotifyEquipmentMsg
	NotifyEquipmentMsgRes
	EquipmentIntensifyMsg
	EquipmentIntensifyMsgRes
	EquipmentDisassembleMsg
	EquipmentDisassembleMsgRes
	EquipmentLevelUpMsg
	EquipmentLevelUpMsgRes
	EquipmentRecastMsg
	EquipmentRecastMsgRes
	EquipmentMakeMsg
	EquipmentMakeMsgRes
	NotifyHeroMsg
	NotifyHeroMsgRes
	HeroOnEquipmentMsg
	HeroOnEquipmentMsgRes
	HeroOffEquipmentMsg
	HeroOffEquipmentMsgRes
	HeroStarLevelUpMsg
	HeroStarLevelUpMsgRes
	HeroSkillLevelUpMsg
	HeroSkillLevelUpMsgRes
	HeroBuyMsg
	HeroBuyMsgRes
	BuildingLevelUpMsg
	BuildingLevelUpMsgRes
	UpdateLineupMsg
	UpdateLineupMsgRes
	AddSoldierMsg
	AddSoldierMsgRes
	NotifySoldierMsg
	NotifySoldierMsgRes
	NotifyUpdateLineupMsg
	NotifyUpdateLineupMsgRes
	SoldierLevelUpMsg
	SoldierLevelUpMsgRes
	SysInformationMsg
	SysInformationMsgRes
	GmMsg
	GmMsgRes
*/
package game_msg

import proto "github.com/golang/protobuf/proto"
import math "math"
import common_msg "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ErrMsgRes struct {
	ErrorCode        *uint32 `protobuf:"varint,1,opt,name=error_code" json:"error_code,omitempty"`
	Cmd              *uint32 `protobuf:"varint,2,opt,name=cmd" json:"cmd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrMsgRes) Reset()         { *m = ErrMsgRes{} }
func (m *ErrMsgRes) String() string { return proto.CompactTextString(m) }
func (*ErrMsgRes) ProtoMessage()    {}

func (m *ErrMsgRes) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ErrMsgRes) GetCmd() uint32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

type LoginMsg struct {
	Platform         *uint32 `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	Account          *string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsg) Reset()         { *m = LoginMsg{} }
func (m *LoginMsg) String() string { return proto.CompactTextString(m) }
func (*LoginMsg) ProtoMessage()    {}

func (m *LoginMsg) GetPlatform() uint32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *LoginMsg) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginMsg) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type LoginMsgRes struct {
	HasRole          *uint32 `protobuf:"varint,1,opt,name=has_role" json:"has_role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginMsgRes) Reset()         { *m = LoginMsgRes{} }
func (m *LoginMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoginMsgRes) ProtoMessage()    {}

func (m *LoginMsgRes) GetHasRole() uint32 {
	if m != nil && m.HasRole != nil {
		return *m.HasRole
	}
	return 0
}

type CreateRoleMsg struct {
	Nick             *string `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRoleMsg) Reset()         { *m = CreateRoleMsg{} }
func (m *CreateRoleMsg) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsg) ProtoMessage()    {}

func (m *CreateRoleMsg) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

type CreateRoleMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateRoleMsgRes) Reset()         { *m = CreateRoleMsgRes{} }
func (m *CreateRoleMsgRes) String() string { return proto.CompactTextString(m) }
func (*CreateRoleMsgRes) ProtoMessage()    {}

type LoadUserMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoadUserMsg) Reset()         { *m = LoadUserMsg{} }
func (m *LoadUserMsg) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsg) ProtoMessage()    {}

type LoadUserMsgRes struct {
	LoadUser         *common_msg.LoadUserT        `protobuf:"bytes,1,opt,name=load_user" json:"load_user,omitempty"`
	Events           []*common_msg.EventT         `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	Mounts           []*common_msg.MountT         `protobuf:"bytes,3,rep,name=mounts" json:"mounts,omitempty"`
	Heros            []*common_msg.HeroT          `protobuf:"bytes,4,rep,name=heros" json:"heros,omitempty"`
	Mails            []*common_msg.MailT          `protobuf:"bytes,5,rep,name=mails" json:"mails,omitempty"`
	Items            []*common_msg.ItemT          `protobuf:"bytes,6,rep,name=items" json:"items,omitempty"`
	Equipments       []*common_msg.EquipmentT     `protobuf:"bytes,7,rep,name=equipments" json:"equipments,omitempty"`
	Buildings        []*common_msg.BuildingT      `protobuf:"bytes,8,rep,name=buildings" json:"buildings,omitempty"`
	Soldiers         []*common_msg.SoldierT       `protobuf:"bytes,9,rep,name=soldiers" json:"soldiers,omitempty"`
	Maps             []*common_msg.MapT           `protobuf:"bytes,10,rep,name=maps" json:"maps,omitempty"`
	PrivateMaps      []*common_msg.PrivateMapT    `protobuf:"bytes,11,rep,name=private_maps" json:"private_maps,omitempty"`
	Lineup           *common_msg.UserLineupT      `protobuf:"bytes,12,opt,name=lineup" json:"lineup,omitempty"`
	HasFairyland     *uint32                      `protobuf:"varint,13,opt,name=has_fairyland" json:"has_fairyland,omitempty"`
	FairylandLineup  *common_msg.FairylandLineupT `protobuf:"bytes,14,opt,name=fairyland_lineup" json:"fairyland_lineup,omitempty"`
	SoldiersLevel    []*common_msg.SoldierLevelT  `protobuf:"bytes,15,rep,name=soldiers_level" json:"soldiers_level,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *LoadUserMsgRes) Reset()         { *m = LoadUserMsgRes{} }
func (m *LoadUserMsgRes) String() string { return proto.CompactTextString(m) }
func (*LoadUserMsgRes) ProtoMessage()    {}

func (m *LoadUserMsgRes) GetLoadUser() *common_msg.LoadUserT {
	if m != nil {
		return m.LoadUser
	}
	return nil
}

func (m *LoadUserMsgRes) GetEvents() []*common_msg.EventT {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *LoadUserMsgRes) GetMounts() []*common_msg.MountT {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *LoadUserMsgRes) GetHeros() []*common_msg.HeroT {
	if m != nil {
		return m.Heros
	}
	return nil
}

func (m *LoadUserMsgRes) GetMails() []*common_msg.MailT {
	if m != nil {
		return m.Mails
	}
	return nil
}

func (m *LoadUserMsgRes) GetItems() []*common_msg.ItemT {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *LoadUserMsgRes) GetEquipments() []*common_msg.EquipmentT {
	if m != nil {
		return m.Equipments
	}
	return nil
}

func (m *LoadUserMsgRes) GetBuildings() []*common_msg.BuildingT {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *LoadUserMsgRes) GetSoldiers() []*common_msg.SoldierT {
	if m != nil {
		return m.Soldiers
	}
	return nil
}

func (m *LoadUserMsgRes) GetMaps() []*common_msg.MapT {
	if m != nil {
		return m.Maps
	}
	return nil
}

func (m *LoadUserMsgRes) GetPrivateMaps() []*common_msg.PrivateMapT {
	if m != nil {
		return m.PrivateMaps
	}
	return nil
}

func (m *LoadUserMsgRes) GetLineup() *common_msg.UserLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

func (m *LoadUserMsgRes) GetHasFairyland() uint32 {
	if m != nil && m.HasFairyland != nil {
		return *m.HasFairyland
	}
	return 0
}

func (m *LoadUserMsgRes) GetFairylandLineup() *common_msg.FairylandLineupT {
	if m != nil {
		return m.FairylandLineup
	}
	return nil
}

func (m *LoadUserMsgRes) GetSoldiersLevel() []*common_msg.SoldierLevelT {
	if m != nil {
		return m.SoldiersLevel
	}
	return nil
}

type LoginMsgEnd struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginMsgEnd) Reset()         { *m = LoginMsgEnd{} }
func (m *LoginMsgEnd) String() string { return proto.CompactTextString(m) }
func (*LoginMsgEnd) ProtoMessage()    {}

// //////////////////////////////////////////////
// 地图
// //////////////////////////////////////////////
type InMapMsg struct {
	Map              *common_msg.MapT `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *InMapMsg) Reset()         { *m = InMapMsg{} }
func (m *InMapMsg) String() string { return proto.CompactTextString(m) }
func (*InMapMsg) ProtoMessage()    {}

func (m *InMapMsg) GetMap() *common_msg.MapT {
	if m != nil {
		return m.Map
	}
	return nil
}

type InMapMsgRes struct {
	Map              *common_msg.MapT `protobuf:"bytes,1,opt,name=map" json:"map,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *InMapMsgRes) Reset()         { *m = InMapMsgRes{} }
func (m *InMapMsgRes) String() string { return proto.CompactTextString(m) }
func (*InMapMsgRes) ProtoMessage()    {}

func (m *InMapMsgRes) GetMap() *common_msg.MapT {
	if m != nil {
		return m.Map
	}
	return nil
}

type NotifyInMapMsgRes struct {
	MapUser          []*common_msg.MapUserT `protobuf:"bytes,1,rep,name=map_user" json:"map_user,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *NotifyInMapMsgRes) Reset()         { *m = NotifyInMapMsgRes{} }
func (m *NotifyInMapMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyInMapMsgRes) ProtoMessage()    {}

func (m *NotifyInMapMsgRes) GetMapUser() []*common_msg.MapUserT {
	if m != nil {
		return m.MapUser
	}
	return nil
}

type NotifyOutMapMsgRes struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyOutMapMsgRes) Reset()         { *m = NotifyOutMapMsgRes{} }
func (m *NotifyOutMapMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyOutMapMsgRes) ProtoMessage()    {}

func (m *NotifyOutMapMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type MapWalkMsg struct {
	X                *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MapWalkMsg) Reset()         { *m = MapWalkMsg{} }
func (m *MapWalkMsg) String() string { return proto.CompactTextString(m) }
func (*MapWalkMsg) ProtoMessage()    {}

func (m *MapWalkMsg) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MapWalkMsg) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MapWalkMsg) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type MapWalkMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MapWalkMsgRes) Reset()         { *m = MapWalkMsgRes{} }
func (m *MapWalkMsgRes) String() string { return proto.CompactTextString(m) }
func (*MapWalkMsgRes) ProtoMessage()    {}

type NotifyMapWalkMsgRes struct {
	Uid              *uint32  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	X                *float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z                *float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *NotifyMapWalkMsgRes) Reset()         { *m = NotifyMapWalkMsgRes{} }
func (m *NotifyMapWalkMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyMapWalkMsgRes) ProtoMessage()    {}

func (m *NotifyMapWalkMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NotifyMapWalkMsgRes) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NotifyMapWalkMsgRes) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *NotifyMapWalkMsgRes) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type NotifyMapChangeMsgRes struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	MountId          *uint32 `protobuf:"varint,2,opt,name=mount_id" json:"mount_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyMapChangeMsgRes) Reset()         { *m = NotifyMapChangeMsgRes{} }
func (m *NotifyMapChangeMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyMapChangeMsgRes) ProtoMessage()    {}

func (m *NotifyMapChangeMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NotifyMapChangeMsgRes) GetMountId() uint32 {
	if m != nil && m.MountId != nil {
		return *m.MountId
	}
	return 0
}

type GetPrivateMapPosMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPrivateMapPosMsg) Reset()         { *m = GetPrivateMapPosMsg{} }
func (m *GetPrivateMapPosMsg) String() string { return proto.CompactTextString(m) }
func (*GetPrivateMapPosMsg) ProtoMessage()    {}

func (m *GetPrivateMapPosMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GetPrivateMapPosMsgRes struct {
	Uid              *uint32                 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Nick             *string                 `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	PrivateMap       *common_msg.PrivateMapT `protobuf:"bytes,3,opt,name=private_map" json:"private_map,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetPrivateMapPosMsgRes) Reset()         { *m = GetPrivateMapPosMsgRes{} }
func (m *GetPrivateMapPosMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetPrivateMapPosMsgRes) ProtoMessage()    {}

func (m *GetPrivateMapPosMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GetPrivateMapPosMsgRes) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *GetPrivateMapPosMsgRes) GetPrivateMap() *common_msg.PrivateMapT {
	if m != nil {
		return m.PrivateMap
	}
	return nil
}

type GetMapDataMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetMapDataMsg) Reset()         { *m = GetMapDataMsg{} }
func (m *GetMapDataMsg) String() string { return proto.CompactTextString(m) }
func (*GetMapDataMsg) ProtoMessage()    {}

type GetMapDataMsgRes struct {
	MapUser          []*common_msg.MapUserT `protobuf:"bytes,1,rep,name=map_user" json:"map_user,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *GetMapDataMsgRes) Reset()         { *m = GetMapDataMsgRes{} }
func (m *GetMapDataMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetMapDataMsgRes) ProtoMessage()    {}

func (m *GetMapDataMsgRes) GetMapUser() []*common_msg.MapUserT {
	if m != nil {
		return m.MapUser
	}
	return nil
}

type OccupyResourcePosMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OccupyResourcePosMsg) Reset()         { *m = OccupyResourcePosMsg{} }
func (m *OccupyResourcePosMsg) String() string { return proto.CompactTextString(m) }
func (*OccupyResourcePosMsg) ProtoMessage()    {}

func (m *OccupyResourcePosMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type OccupyResourcePosMsgRes struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OccupyResourcePosMsgRes) Reset()         { *m = OccupyResourcePosMsgRes{} }
func (m *OccupyResourcePosMsgRes) String() string { return proto.CompactTextString(m) }
func (*OccupyResourcePosMsgRes) ProtoMessage()    {}

func (m *OccupyResourcePosMsgRes) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GetResourcePosMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetResourcePosMsg) Reset()         { *m = GetResourcePosMsg{} }
func (m *GetResourcePosMsg) String() string { return proto.CompactTextString(m) }
func (*GetResourcePosMsg) ProtoMessage()    {}

func (m *GetResourcePosMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GetResourcePosMsgRes struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetResourcePosMsgRes) Reset()         { *m = GetResourcePosMsgRes{} }
func (m *GetResourcePosMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetResourcePosMsgRes) ProtoMessage()    {}

func (m *GetResourcePosMsgRes) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type UpdateResourceLineupMsg struct {
	Pos              *uint32                     `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Lineup           *common_msg.ResourceLineupT `protobuf:"bytes,2,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *UpdateResourceLineupMsg) Reset()         { *m = UpdateResourceLineupMsg{} }
func (m *UpdateResourceLineupMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceLineupMsg) ProtoMessage()    {}

func (m *UpdateResourceLineupMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *UpdateResourceLineupMsg) GetLineup() *common_msg.ResourceLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type UpdateResourceLineupMsgRes struct {
	Pos              *uint32                     `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Lineup           *common_msg.ResourceLineupT `protobuf:"bytes,2,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *UpdateResourceLineupMsgRes) Reset()         { *m = UpdateResourceLineupMsgRes{} }
func (m *UpdateResourceLineupMsgRes) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceLineupMsgRes) ProtoMessage()    {}

func (m *UpdateResourceLineupMsgRes) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *UpdateResourceLineupMsgRes) GetLineup() *common_msg.ResourceLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type GetPrivateMapItemPosMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPrivateMapItemPosMsg) Reset()         { *m = GetPrivateMapItemPosMsg{} }
func (m *GetPrivateMapItemPosMsg) String() string { return proto.CompactTextString(m) }
func (*GetPrivateMapItemPosMsg) ProtoMessage()    {}

func (m *GetPrivateMapItemPosMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GetPrivateMapItemPosMsgRes struct {
	Pos              *uint32             `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	Reward           *common_msg.RewardT `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GetPrivateMapItemPosMsgRes) Reset()         { *m = GetPrivateMapItemPosMsgRes{} }
func (m *GetPrivateMapItemPosMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetPrivateMapItemPosMsgRes) ProtoMessage()    {}

func (m *GetPrivateMapItemPosMsgRes) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *GetPrivateMapItemPosMsgRes) GetReward() *common_msg.RewardT {
	if m != nil {
		return m.Reward
	}
	return nil
}

type OpenFairylandMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OpenFairylandMsg) Reset()         { *m = OpenFairylandMsg{} }
func (m *OpenFairylandMsg) String() string { return proto.CompactTextString(m) }
func (*OpenFairylandMsg) ProtoMessage()    {}

type OpenFairylandMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OpenFairylandMsgRes) Reset()         { *m = OpenFairylandMsgRes{} }
func (m *OpenFairylandMsgRes) String() string { return proto.CompactTextString(m) }
func (*OpenFairylandMsgRes) ProtoMessage()    {}

type GetBtlSceneMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetBtlSceneMsg) Reset()         { *m = GetBtlSceneMsg{} }
func (m *GetBtlSceneMsg) String() string { return proto.CompactTextString(m) }
func (*GetBtlSceneMsg) ProtoMessage()    {}

type GetBtlSceneMsgRes struct {
	BtlSceneId       []uint32 `protobuf:"varint,1,rep,name=btl_scene_id" json:"btl_scene_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetBtlSceneMsgRes) Reset()         { *m = GetBtlSceneMsgRes{} }
func (m *GetBtlSceneMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetBtlSceneMsgRes) ProtoMessage()    {}

func (m *GetBtlSceneMsgRes) GetBtlSceneId() []uint32 {
	if m != nil {
		return m.BtlSceneId
	}
	return nil
}

type UpdateFairylandLineupMsg struct {
	Lineup           *common_msg.FairylandLineupT `protobuf:"bytes,2,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *UpdateFairylandLineupMsg) Reset()         { *m = UpdateFairylandLineupMsg{} }
func (m *UpdateFairylandLineupMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateFairylandLineupMsg) ProtoMessage()    {}

func (m *UpdateFairylandLineupMsg) GetLineup() *common_msg.FairylandLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type UpdateFairylandLineupMsgRes struct {
	Lineup           *common_msg.FairylandLineupT `protobuf:"bytes,2,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *UpdateFairylandLineupMsgRes) Reset()         { *m = UpdateFairylandLineupMsgRes{} }
func (m *UpdateFairylandLineupMsgRes) String() string { return proto.CompactTextString(m) }
func (*UpdateFairylandLineupMsgRes) ProtoMessage()    {}

func (m *UpdateFairylandLineupMsgRes) GetLineup() *common_msg.FairylandLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type GetOfflineUserPrivateMapMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetOfflineUserPrivateMapMsg) Reset()         { *m = GetOfflineUserPrivateMapMsg{} }
func (m *GetOfflineUserPrivateMapMsg) String() string { return proto.CompactTextString(m) }
func (*GetOfflineUserPrivateMapMsg) ProtoMessage()    {}

type GetOfflineUserPrivateMapMsgRes struct {
	OfflineUserPrivateMap []*common_msg.CliOfflineUserPrivateMapT `protobuf:"bytes,1,rep,name=offline_user_private_map" json:"offline_user_private_map,omitempty"`
	XXX_unrecognized      []byte                                  `json:"-"`
}

func (m *GetOfflineUserPrivateMapMsgRes) Reset()         { *m = GetOfflineUserPrivateMapMsgRes{} }
func (m *GetOfflineUserPrivateMapMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetOfflineUserPrivateMapMsgRes) ProtoMessage()    {}

func (m *GetOfflineUserPrivateMapMsgRes) GetOfflineUserPrivateMap() []*common_msg.CliOfflineUserPrivateMapT {
	if m != nil {
		return m.OfflineUserPrivateMap
	}
	return nil
}

type NotifyKickOutMapMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyKickOutMapMsg) Reset()         { *m = NotifyKickOutMapMsg{} }
func (m *NotifyKickOutMapMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyKickOutMapMsg) ProtoMessage()    {}

type NotifyKickOutMapMsgRes struct {
	Uid              *uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyKickOutMapMsgRes) Reset()         { *m = NotifyKickOutMapMsgRes{} }
func (m *NotifyKickOutMapMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyKickOutMapMsgRes) ProtoMessage()    {}

func (m *NotifyKickOutMapMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type NotifyPrivateMapBtlMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyPrivateMapBtlMsg) Reset()         { *m = NotifyPrivateMapBtlMsg{} }
func (m *NotifyPrivateMapBtlMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyPrivateMapBtlMsg) ProtoMessage()    {}

type NotifyPrivateMapBtlMsgRes struct {
	Uid                   *uint32                                 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	OfflineUserPrivateMap []*common_msg.CliOfflineUserPrivateMapT `protobuf:"bytes,2,rep,name=offline_user_private_map" json:"offline_user_private_map,omitempty"`
	XXX_unrecognized      []byte                                  `json:"-"`
}

func (m *NotifyPrivateMapBtlMsgRes) Reset()         { *m = NotifyPrivateMapBtlMsgRes{} }
func (m *NotifyPrivateMapBtlMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyPrivateMapBtlMsgRes) ProtoMessage()    {}

func (m *NotifyPrivateMapBtlMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NotifyPrivateMapBtlMsgRes) GetOfflineUserPrivateMap() []*common_msg.CliOfflineUserPrivateMapT {
	if m != nil {
		return m.OfflineUserPrivateMap
	}
	return nil
}

type PrivateMapBagMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PrivateMapBagMsg) Reset()         { *m = PrivateMapBagMsg{} }
func (m *PrivateMapBagMsg) String() string { return proto.CompactTextString(m) }
func (*PrivateMapBagMsg) ProtoMessage()    {}

type PrivateMapBagMsgRes struct {
	Item             []*common_msg.ItemT      `protobuf:"bytes,1,rep,name=item" json:"item,omitempty"`
	Equipment        []*common_msg.EquipmentT `protobuf:"bytes,2,rep,name=equipment" json:"equipment,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *PrivateMapBagMsgRes) Reset()         { *m = PrivateMapBagMsgRes{} }
func (m *PrivateMapBagMsgRes) String() string { return proto.CompactTextString(m) }
func (*PrivateMapBagMsgRes) ProtoMessage()    {}

func (m *PrivateMapBagMsgRes) GetItem() []*common_msg.ItemT {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *PrivateMapBagMsgRes) GetEquipment() []*common_msg.EquipmentT {
	if m != nil {
		return m.Equipment
	}
	return nil
}

// //////////////////////////////////////////////
// 聊天
// //////////////////////////////////////////////
type ChatMsg struct {
	Type             *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Msg              *string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}

func (m *ChatMsg) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ChatMsg) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ChatMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type ChatMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChatMsgRes) Reset()         { *m = ChatMsgRes{} }
func (m *ChatMsgRes) String() string { return proto.CompactTextString(m) }
func (*ChatMsgRes) ProtoMessage()    {}

type NotifyChatMsgRes struct {
	Type             *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Nick             *string `protobuf:"bytes,3,opt,name=nick" json:"nick,omitempty"`
	Msg              *string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyChatMsgRes) Reset()         { *m = NotifyChatMsgRes{} }
func (m *NotifyChatMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyChatMsgRes) ProtoMessage()    {}

func (m *NotifyChatMsgRes) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *NotifyChatMsgRes) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *NotifyChatMsgRes) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *NotifyChatMsgRes) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

// //////////////////////////////////////////////
// 坐骑
// //////////////////////////////////////////////
type OnMountMsg struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OnMountMsg) Reset()         { *m = OnMountMsg{} }
func (m *OnMountMsg) String() string { return proto.CompactTextString(m) }
func (*OnMountMsg) ProtoMessage()    {}

func (m *OnMountMsg) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type OnMountMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OnMountMsgRes) Reset()         { *m = OnMountMsgRes{} }
func (m *OnMountMsgRes) String() string { return proto.CompactTextString(m) }
func (*OnMountMsgRes) ProtoMessage()    {}

type OffMountMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OffMountMsg) Reset()         { *m = OffMountMsg{} }
func (m *OffMountMsg) String() string { return proto.CompactTextString(m) }
func (*OffMountMsg) ProtoMessage()    {}

type OffMountMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OffMountMsgRes) Reset()         { *m = OffMountMsgRes{} }
func (m *OffMountMsgRes) String() string { return proto.CompactTextString(m) }
func (*OffMountMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 任务
// //////////////////////////////////////////////
type AcceptTaskMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AcceptTaskMsg) Reset()         { *m = AcceptTaskMsg{} }
func (m *AcceptTaskMsg) String() string { return proto.CompactTextString(m) }
func (*AcceptTaskMsg) ProtoMessage()    {}

type AcceptTaskMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AcceptTaskMsgRes) Reset()         { *m = AcceptTaskMsgRes{} }
func (m *AcceptTaskMsgRes) String() string { return proto.CompactTextString(m) }
func (*AcceptTaskMsgRes) ProtoMessage()    {}

type FinishTaskMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishTaskMsg) Reset()         { *m = FinishTaskMsg{} }
func (m *FinishTaskMsg) String() string { return proto.CompactTextString(m) }
func (*FinishTaskMsg) ProtoMessage()    {}

type FinishTaskMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishTaskMsgRes) Reset()         { *m = FinishTaskMsgRes{} }
func (m *FinishTaskMsgRes) String() string { return proto.CompactTextString(m) }
func (*FinishTaskMsgRes) ProtoMessage()    {}

type RewardTaskMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RewardTaskMsg) Reset()         { *m = RewardTaskMsg{} }
func (m *RewardTaskMsg) String() string { return proto.CompactTextString(m) }
func (*RewardTaskMsg) ProtoMessage()    {}

type RewardTaskMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RewardTaskMsgRes) Reset()         { *m = RewardTaskMsgRes{} }
func (m *RewardTaskMsgRes) String() string { return proto.CompactTextString(m) }
func (*RewardTaskMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 事件
// //////////////////////////////////////////////
type UpdateEventMsg struct {
	Event            *common_msg.EventT `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UpdateEventMsg) Reset()         { *m = UpdateEventMsg{} }
func (m *UpdateEventMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateEventMsg) ProtoMessage()    {}

func (m *UpdateEventMsg) GetEvent() *common_msg.EventT {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateEventMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateEventMsgRes) Reset()         { *m = UpdateEventMsgRes{} }
func (m *UpdateEventMsgRes) String() string { return proto.CompactTextString(m) }
func (*UpdateEventMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 邮件
// //////////////////////////////////////////////
type MailReadMsg struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MailReadMsg) Reset()         { *m = MailReadMsg{} }
func (m *MailReadMsg) String() string { return proto.CompactTextString(m) }
func (*MailReadMsg) ProtoMessage()    {}

func (m *MailReadMsg) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type MailReadMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MailReadMsgRes) Reset()         { *m = MailReadMsgRes{} }
func (m *MailReadMsgRes) String() string { return proto.CompactTextString(m) }
func (*MailReadMsgRes) ProtoMessage()    {}

type MailDelMsg struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MailDelMsg) Reset()         { *m = MailDelMsg{} }
func (m *MailDelMsg) String() string { return proto.CompactTextString(m) }
func (*MailDelMsg) ProtoMessage()    {}

func (m *MailDelMsg) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type MailDelMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MailDelMsgRes) Reset()         { *m = MailDelMsgRes{} }
func (m *MailDelMsgRes) String() string { return proto.CompactTextString(m) }
func (*MailDelMsgRes) ProtoMessage()    {}

type MailAttachmentMsg struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MailAttachmentMsg) Reset()         { *m = MailAttachmentMsg{} }
func (m *MailAttachmentMsg) String() string { return proto.CompactTextString(m) }
func (*MailAttachmentMsg) ProtoMessage()    {}

func (m *MailAttachmentMsg) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type MailAttachmentMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MailAttachmentMsgRes) Reset()         { *m = MailAttachmentMsgRes{} }
func (m *MailAttachmentMsgRes) String() string { return proto.CompactTextString(m) }
func (*MailAttachmentMsgRes) ProtoMessage()    {}

type NotifyMailMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyMailMsg) Reset()         { *m = NotifyMailMsg{} }
func (m *NotifyMailMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyMailMsg) ProtoMessage()    {}

type NotifyMailMsgRes struct {
	Mail             *common_msg.MailT `protobuf:"bytes,1,opt,name=mail" json:"mail,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NotifyMailMsgRes) Reset()         { *m = NotifyMailMsgRes{} }
func (m *NotifyMailMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyMailMsgRes) ProtoMessage()    {}

func (m *NotifyMailMsgRes) GetMail() *common_msg.MailT {
	if m != nil {
		return m.Mail
	}
	return nil
}

// 战斗cmd, 区间[0x00010801,0x10FFF]战斗中只能发送战斗相关消息
// //////////////////////////////////////////////
// 战场
// //////////////////////////////////////////////
type BtlServerOfflineMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlServerOfflineMsg) Reset()         { *m = BtlServerOfflineMsg{} }
func (m *BtlServerOfflineMsg) String() string { return proto.CompactTextString(m) }
func (*BtlServerOfflineMsg) ProtoMessage()    {}

type BtlServerOfflineMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlServerOfflineMsgRes) Reset()         { *m = BtlServerOfflineMsgRes{} }
func (m *BtlServerOfflineMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlServerOfflineMsgRes) ProtoMessage()    {}

type BtlPrivateMapInMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtlPrivateMapInMsg) Reset()         { *m = BtlPrivateMapInMsg{} }
func (m *BtlPrivateMapInMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapInMsg) ProtoMessage()    {}

func (m *BtlPrivateMapInMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type BtlPrivateMapInMsgRes struct {
	PveIngReward     []*common_msg.PveIngRewardT `protobuf:"bytes,1,rep,name=pve_ing_reward" json:"pve_ing_reward,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *BtlPrivateMapInMsgRes) Reset()         { *m = BtlPrivateMapInMsgRes{} }
func (m *BtlPrivateMapInMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapInMsgRes) ProtoMessage()    {}

func (m *BtlPrivateMapInMsgRes) GetPveIngReward() []*common_msg.PveIngRewardT {
	if m != nil {
		return m.PveIngReward
	}
	return nil
}

type BtlPrivateOutMsg struct {
	Ret              *uint32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DieSoldierId     []uint32 `protobuf:"varint,2,rep,name=die_soldier_id" json:"die_soldier_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtlPrivateOutMsg) Reset()         { *m = BtlPrivateOutMsg{} }
func (m *BtlPrivateOutMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateOutMsg) ProtoMessage()    {}

func (m *BtlPrivateOutMsg) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *BtlPrivateOutMsg) GetDieSoldierId() []uint32 {
	if m != nil {
		return m.DieSoldierId
	}
	return nil
}

type BtlPrivateOutMsgRes struct {
	EndReward        *common_msg.RewardT `protobuf:"bytes,1,opt,name=end_reward" json:"end_reward,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BtlPrivateOutMsgRes) Reset()         { *m = BtlPrivateOutMsgRes{} }
func (m *BtlPrivateOutMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateOutMsgRes) ProtoMessage()    {}

func (m *BtlPrivateOutMsgRes) GetEndReward() *common_msg.RewardT {
	if m != nil {
		return m.EndReward
	}
	return nil
}

type BtlPrivateMapFairylandInMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlPrivateMapFairylandInMsg) Reset()         { *m = BtlPrivateMapFairylandInMsg{} }
func (m *BtlPrivateMapFairylandInMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapFairylandInMsg) ProtoMessage()    {}

type BtlPrivateMapFairylandInMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlPrivateMapFairylandInMsgRes) Reset()         { *m = BtlPrivateMapFairylandInMsgRes{} }
func (m *BtlPrivateMapFairylandInMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapFairylandInMsgRes) ProtoMessage()    {}

type BtlPrivateMapFairylandOutMsg struct {
	Ret              *uint32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DieSoldierId     []uint32 `protobuf:"varint,2,rep,name=die_soldier_id" json:"die_soldier_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtlPrivateMapFairylandOutMsg) Reset()         { *m = BtlPrivateMapFairylandOutMsg{} }
func (m *BtlPrivateMapFairylandOutMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapFairylandOutMsg) ProtoMessage()    {}

func (m *BtlPrivateMapFairylandOutMsg) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *BtlPrivateMapFairylandOutMsg) GetDieSoldierId() []uint32 {
	if m != nil {
		return m.DieSoldierId
	}
	return nil
}

type BtlPrivateMapFairylandOutMsgRes struct {
	EndReward        *common_msg.RewardT `protobuf:"bytes,1,opt,name=end_reward" json:"end_reward,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BtlPrivateMapFairylandOutMsgRes) Reset()         { *m = BtlPrivateMapFairylandOutMsgRes{} }
func (m *BtlPrivateMapFairylandOutMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapFairylandOutMsgRes) ProtoMessage()    {}

func (m *BtlPrivateMapFairylandOutMsgRes) GetEndReward() *common_msg.RewardT {
	if m != nil {
		return m.EndReward
	}
	return nil
}

type BtlPrivateMapPeerInMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtlPrivateMapPeerInMsg) Reset()         { *m = BtlPrivateMapPeerInMsg{} }
func (m *BtlPrivateMapPeerInMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerInMsg) ProtoMessage()    {}

func (m *BtlPrivateMapPeerInMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type BtlPrivateMapPeerInMsgRes struct {
	PveIngReward     []*common_msg.PveIngRewardT `protobuf:"bytes,1,rep,name=pve_ing_reward" json:"pve_ing_reward,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *BtlPrivateMapPeerInMsgRes) Reset()         { *m = BtlPrivateMapPeerInMsgRes{} }
func (m *BtlPrivateMapPeerInMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerInMsgRes) ProtoMessage()    {}

func (m *BtlPrivateMapPeerInMsgRes) GetPveIngReward() []*common_msg.PveIngRewardT {
	if m != nil {
		return m.PveIngReward
	}
	return nil
}

type BtlPrivateMapPeerOutMsg struct {
	Ret              *uint32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DieSoldierId     []uint32 `protobuf:"varint,2,rep,name=die_soldier_id" json:"die_soldier_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtlPrivateMapPeerOutMsg) Reset()         { *m = BtlPrivateMapPeerOutMsg{} }
func (m *BtlPrivateMapPeerOutMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerOutMsg) ProtoMessage()    {}

func (m *BtlPrivateMapPeerOutMsg) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *BtlPrivateMapPeerOutMsg) GetDieSoldierId() []uint32 {
	if m != nil {
		return m.DieSoldierId
	}
	return nil
}

type BtlPrivateMapPeerOutMsgRes struct {
	EndReward        *common_msg.RewardT `protobuf:"bytes,1,opt,name=end_reward" json:"end_reward,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BtlPrivateMapPeerOutMsgRes) Reset()         { *m = BtlPrivateMapPeerOutMsgRes{} }
func (m *BtlPrivateMapPeerOutMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerOutMsgRes) ProtoMessage()    {}

func (m *BtlPrivateMapPeerOutMsgRes) GetEndReward() *common_msg.RewardT {
	if m != nil {
		return m.EndReward
	}
	return nil
}

type BtlPrivateMapPeerResourcesInMsg struct {
	Pos              *uint32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BtlPrivateMapPeerResourcesInMsg) Reset()         { *m = BtlPrivateMapPeerResourcesInMsg{} }
func (m *BtlPrivateMapPeerResourcesInMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerResourcesInMsg) ProtoMessage()    {}

func (m *BtlPrivateMapPeerResourcesInMsg) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type BtlPrivateMapPeerResourcesInMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlPrivateMapPeerResourcesInMsgRes) Reset()         { *m = BtlPrivateMapPeerResourcesInMsgRes{} }
func (m *BtlPrivateMapPeerResourcesInMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerResourcesInMsgRes) ProtoMessage()    {}

type BtlPrivateMapPeerResourcesOutMsg struct {
	Ret              *uint32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DieSoldierId     []uint32 `protobuf:"varint,2,rep,name=die_soldier_id" json:"die_soldier_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtlPrivateMapPeerResourcesOutMsg) Reset()         { *m = BtlPrivateMapPeerResourcesOutMsg{} }
func (m *BtlPrivateMapPeerResourcesOutMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerResourcesOutMsg) ProtoMessage()    {}

func (m *BtlPrivateMapPeerResourcesOutMsg) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *BtlPrivateMapPeerResourcesOutMsg) GetDieSoldierId() []uint32 {
	if m != nil {
		return m.DieSoldierId
	}
	return nil
}

type BtlPrivateMapPeerResourcesOutMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BtlPrivateMapPeerResourcesOutMsgRes) Reset()         { *m = BtlPrivateMapPeerResourcesOutMsgRes{} }
func (m *BtlPrivateMapPeerResourcesOutMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerResourcesOutMsgRes) ProtoMessage()    {}

type BtlPrivateMapPeerDuelOutMsg struct {
	Ret              *uint32  `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	DieSoldierId     []uint32 `protobuf:"varint,2,rep,name=die_soldier_id" json:"die_soldier_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BtlPrivateMapPeerDuelOutMsg) Reset()         { *m = BtlPrivateMapPeerDuelOutMsg{} }
func (m *BtlPrivateMapPeerDuelOutMsg) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerDuelOutMsg) ProtoMessage()    {}

func (m *BtlPrivateMapPeerDuelOutMsg) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *BtlPrivateMapPeerDuelOutMsg) GetDieSoldierId() []uint32 {
	if m != nil {
		return m.DieSoldierId
	}
	return nil
}

type BtlPrivateMapPeerDuelOutMsgRes struct {
	Reward           *common_msg.RewardT `protobuf:"bytes,1,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *BtlPrivateMapPeerDuelOutMsgRes) Reset()         { *m = BtlPrivateMapPeerDuelOutMsgRes{} }
func (m *BtlPrivateMapPeerDuelOutMsgRes) String() string { return proto.CompactTextString(m) }
func (*BtlPrivateMapPeerDuelOutMsgRes) ProtoMessage()    {}

func (m *BtlPrivateMapPeerDuelOutMsgRes) GetReward() *common_msg.RewardT {
	if m != nil {
		return m.Reward
	}
	return nil
}

// //////////////////////////////////////////////
// 道具
// //////////////////////////////////////////////
type NotifyItemMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyItemMsg) Reset()         { *m = NotifyItemMsg{} }
func (m *NotifyItemMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyItemMsg) ProtoMessage()    {}

type NotifyItemMsgRes struct {
	Items            *common_msg.ItemT `protobuf:"bytes,1,opt,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NotifyItemMsgRes) Reset()         { *m = NotifyItemMsgRes{} }
func (m *NotifyItemMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyItemMsgRes) ProtoMessage()    {}

func (m *NotifyItemMsgRes) GetItems() *common_msg.ItemT {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetForageItemMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetForageItemMsg) Reset()         { *m = GetForageItemMsg{} }
func (m *GetForageItemMsg) String() string { return proto.CompactTextString(m) }
func (*GetForageItemMsg) ProtoMessage()    {}

type GetForageItemMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetForageItemMsgRes) Reset()         { *m = GetForageItemMsgRes{} }
func (m *GetForageItemMsgRes) String() string { return proto.CompactTextString(m) }
func (*GetForageItemMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 装备
// //////////////////////////////////////////////
type EquipmentDelMsg struct {
	Idx              *uint32 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EquipmentDelMsg) Reset()         { *m = EquipmentDelMsg{} }
func (m *EquipmentDelMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentDelMsg) ProtoMessage()    {}

func (m *EquipmentDelMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type EquipmentDelMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EquipmentDelMsgRes) Reset()         { *m = EquipmentDelMsgRes{} }
func (m *EquipmentDelMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentDelMsgRes) ProtoMessage()    {}

type NotifyEquipmentMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyEquipmentMsg) Reset()         { *m = NotifyEquipmentMsg{} }
func (m *NotifyEquipmentMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyEquipmentMsg) ProtoMessage()    {}

type NotifyEquipmentMsgRes struct {
	Equipment        []*common_msg.EquipmentT `protobuf:"bytes,1,rep,name=equipment" json:"equipment,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *NotifyEquipmentMsgRes) Reset()         { *m = NotifyEquipmentMsgRes{} }
func (m *NotifyEquipmentMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyEquipmentMsgRes) ProtoMessage()    {}

func (m *NotifyEquipmentMsgRes) GetEquipment() []*common_msg.EquipmentT {
	if m != nil {
		return m.Equipment
	}
	return nil
}

type EquipmentIntensifyMsg struct {
	Idx               *uint32  `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	UseIdxs           []uint32 `protobuf:"varint,2,rep,name=use_idxs" json:"use_idxs,omitempty"`
	IsUseEquipmentExp *uint32  `protobuf:"varint,3,opt,name=is_use_equipment_exp" json:"is_use_equipment_exp,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *EquipmentIntensifyMsg) Reset()         { *m = EquipmentIntensifyMsg{} }
func (m *EquipmentIntensifyMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentIntensifyMsg) ProtoMessage()    {}

func (m *EquipmentIntensifyMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *EquipmentIntensifyMsg) GetUseIdxs() []uint32 {
	if m != nil {
		return m.UseIdxs
	}
	return nil
}

func (m *EquipmentIntensifyMsg) GetIsUseEquipmentExp() uint32 {
	if m != nil && m.IsUseEquipmentExp != nil {
		return *m.IsUseEquipmentExp
	}
	return 0
}

type EquipmentIntensifyMsgRes struct {
	DelMoney         *uint32 `protobuf:"varint,1,opt,name=del_money" json:"del_money,omitempty"`
	AddExp           *uint32 `protobuf:"varint,2,opt,name=add_exp" json:"add_exp,omitempty"`
	EquipmentExp     *uint32 `protobuf:"varint,3,opt,name=equipment_exp" json:"equipment_exp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EquipmentIntensifyMsgRes) Reset()         { *m = EquipmentIntensifyMsgRes{} }
func (m *EquipmentIntensifyMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentIntensifyMsgRes) ProtoMessage()    {}

func (m *EquipmentIntensifyMsgRes) GetDelMoney() uint32 {
	if m != nil && m.DelMoney != nil {
		return *m.DelMoney
	}
	return 0
}

func (m *EquipmentIntensifyMsgRes) GetAddExp() uint32 {
	if m != nil && m.AddExp != nil {
		return *m.AddExp
	}
	return 0
}

func (m *EquipmentIntensifyMsgRes) GetEquipmentExp() uint32 {
	if m != nil && m.EquipmentExp != nil {
		return *m.EquipmentExp
	}
	return 0
}

type EquipmentDisassembleMsg struct {
	Idxs             []uint32 `protobuf:"varint,1,rep,name=idxs" json:"idxs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EquipmentDisassembleMsg) Reset()         { *m = EquipmentDisassembleMsg{} }
func (m *EquipmentDisassembleMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentDisassembleMsg) ProtoMessage()    {}

func (m *EquipmentDisassembleMsg) GetIdxs() []uint32 {
	if m != nil {
		return m.Idxs
	}
	return nil
}

type EquipmentDisassembleMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EquipmentDisassembleMsgRes) Reset()         { *m = EquipmentDisassembleMsgRes{} }
func (m *EquipmentDisassembleMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentDisassembleMsgRes) ProtoMessage()    {}

type EquipmentLevelUpMsg struct {
	Idx              *uint32 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	AddExp           *uint32 `protobuf:"varint,2,opt,name=add_exp" json:"add_exp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EquipmentLevelUpMsg) Reset()         { *m = EquipmentLevelUpMsg{} }
func (m *EquipmentLevelUpMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentLevelUpMsg) ProtoMessage()    {}

func (m *EquipmentLevelUpMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *EquipmentLevelUpMsg) GetAddExp() uint32 {
	if m != nil && m.AddExp != nil {
		return *m.AddExp
	}
	return 0
}

type EquipmentLevelUpMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EquipmentLevelUpMsgRes) Reset()         { *m = EquipmentLevelUpMsgRes{} }
func (m *EquipmentLevelUpMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentLevelUpMsgRes) ProtoMessage()    {}

type EquipmentRecastMsg struct {
	Idx              *uint32 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EquipmentRecastMsg) Reset()         { *m = EquipmentRecastMsg{} }
func (m *EquipmentRecastMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentRecastMsg) ProtoMessage()    {}

func (m *EquipmentRecastMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type EquipmentRecastMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EquipmentRecastMsgRes) Reset()         { *m = EquipmentRecastMsgRes{} }
func (m *EquipmentRecastMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentRecastMsgRes) ProtoMessage()    {}

type EquipmentMakeMsg struct {
	Blueprint        *uint32 `protobuf:"varint,1,opt,name=blueprint" json:"blueprint,omitempty"`
	IsAdvanced       *uint32 `protobuf:"varint,2,opt,name=is_advanced" json:"is_advanced,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EquipmentMakeMsg) Reset()         { *m = EquipmentMakeMsg{} }
func (m *EquipmentMakeMsg) String() string { return proto.CompactTextString(m) }
func (*EquipmentMakeMsg) ProtoMessage()    {}

func (m *EquipmentMakeMsg) GetBlueprint() uint32 {
	if m != nil && m.Blueprint != nil {
		return *m.Blueprint
	}
	return 0
}

func (m *EquipmentMakeMsg) GetIsAdvanced() uint32 {
	if m != nil && m.IsAdvanced != nil {
		return *m.IsAdvanced
	}
	return 0
}

type EquipmentMakeMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EquipmentMakeMsgRes) Reset()         { *m = EquipmentMakeMsgRes{} }
func (m *EquipmentMakeMsgRes) String() string { return proto.CompactTextString(m) }
func (*EquipmentMakeMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 英雄
// //////////////////////////////////////////////
type NotifyHeroMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyHeroMsg) Reset()         { *m = NotifyHeroMsg{} }
func (m *NotifyHeroMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyHeroMsg) ProtoMessage()    {}

type NotifyHeroMsgRes struct {
	Hero             *common_msg.HeroT `protobuf:"bytes,1,opt,name=hero" json:"hero,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NotifyHeroMsgRes) Reset()         { *m = NotifyHeroMsgRes{} }
func (m *NotifyHeroMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyHeroMsgRes) ProtoMessage()    {}

func (m *NotifyHeroMsgRes) GetHero() *common_msg.HeroT {
	if m != nil {
		return m.Hero
	}
	return nil
}

type HeroOnEquipmentMsg struct {
	Idx              *uint32 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	HeroId           *uint32 `protobuf:"varint,2,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroOnEquipmentMsg) Reset()         { *m = HeroOnEquipmentMsg{} }
func (m *HeroOnEquipmentMsg) String() string { return proto.CompactTextString(m) }
func (*HeroOnEquipmentMsg) ProtoMessage()    {}

func (m *HeroOnEquipmentMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *HeroOnEquipmentMsg) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type HeroOnEquipmentMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroOnEquipmentMsgRes) Reset()         { *m = HeroOnEquipmentMsgRes{} }
func (m *HeroOnEquipmentMsgRes) String() string { return proto.CompactTextString(m) }
func (*HeroOnEquipmentMsgRes) ProtoMessage()    {}

type HeroOffEquipmentMsg struct {
	Idx              *uint32 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	HeroId           *uint32 `protobuf:"varint,2,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroOffEquipmentMsg) Reset()         { *m = HeroOffEquipmentMsg{} }
func (m *HeroOffEquipmentMsg) String() string { return proto.CompactTextString(m) }
func (*HeroOffEquipmentMsg) ProtoMessage()    {}

func (m *HeroOffEquipmentMsg) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *HeroOffEquipmentMsg) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type HeroOffEquipmentMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroOffEquipmentMsgRes) Reset()         { *m = HeroOffEquipmentMsgRes{} }
func (m *HeroOffEquipmentMsgRes) String() string { return proto.CompactTextString(m) }
func (*HeroOffEquipmentMsgRes) ProtoMessage()    {}

type HeroStarLevelUpMsg struct {
	HeroId           *uint32 `protobuf:"varint,1,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroStarLevelUpMsg) Reset()         { *m = HeroStarLevelUpMsg{} }
func (m *HeroStarLevelUpMsg) String() string { return proto.CompactTextString(m) }
func (*HeroStarLevelUpMsg) ProtoMessage()    {}

func (m *HeroStarLevelUpMsg) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type HeroStarLevelUpMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroStarLevelUpMsgRes) Reset()         { *m = HeroStarLevelUpMsgRes{} }
func (m *HeroStarLevelUpMsgRes) String() string { return proto.CompactTextString(m) }
func (*HeroStarLevelUpMsgRes) ProtoMessage()    {}

type HeroSkillLevelUpMsg struct {
	HeroId           *uint32 `protobuf:"varint,1,opt,name=hero_id" json:"hero_id,omitempty"`
	SkillIdx         *uint32 `protobuf:"varint,2,opt,name=skill_idx" json:"skill_idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroSkillLevelUpMsg) Reset()         { *m = HeroSkillLevelUpMsg{} }
func (m *HeroSkillLevelUpMsg) String() string { return proto.CompactTextString(m) }
func (*HeroSkillLevelUpMsg) ProtoMessage()    {}

func (m *HeroSkillLevelUpMsg) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *HeroSkillLevelUpMsg) GetSkillIdx() uint32 {
	if m != nil && m.SkillIdx != nil {
		return *m.SkillIdx
	}
	return 0
}

type HeroSkillLevelUpMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroSkillLevelUpMsgRes) Reset()         { *m = HeroSkillLevelUpMsgRes{} }
func (m *HeroSkillLevelUpMsgRes) String() string { return proto.CompactTextString(m) }
func (*HeroSkillLevelUpMsgRes) ProtoMessage()    {}

type HeroBuyMsg struct {
	HeroId           *uint32 `protobuf:"varint,1,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroBuyMsg) Reset()         { *m = HeroBuyMsg{} }
func (m *HeroBuyMsg) String() string { return proto.CompactTextString(m) }
func (*HeroBuyMsg) ProtoMessage()    {}

func (m *HeroBuyMsg) GetHeroId() uint32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

type HeroBuyMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeroBuyMsgRes) Reset()         { *m = HeroBuyMsgRes{} }
func (m *HeroBuyMsgRes) String() string { return proto.CompactTextString(m) }
func (*HeroBuyMsgRes) ProtoMessage()    {}

// //////////////////////////////////////////////
// 建筑
// //////////////////////////////////////////////
type BuildingLevelUpMsg struct {
	BuildingId       *uint32 `protobuf:"varint,1,opt,name=building_id" json:"building_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuildingLevelUpMsg) Reset()         { *m = BuildingLevelUpMsg{} }
func (m *BuildingLevelUpMsg) String() string { return proto.CompactTextString(m) }
func (*BuildingLevelUpMsg) ProtoMessage()    {}

func (m *BuildingLevelUpMsg) GetBuildingId() uint32 {
	if m != nil && m.BuildingId != nil {
		return *m.BuildingId
	}
	return 0
}

type BuildingLevelUpMsgRes struct {
	Building         *common_msg.BuildingT `protobuf:"bytes,1,opt,name=building" json:"building,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *BuildingLevelUpMsgRes) Reset()         { *m = BuildingLevelUpMsgRes{} }
func (m *BuildingLevelUpMsgRes) String() string { return proto.CompactTextString(m) }
func (*BuildingLevelUpMsgRes) ProtoMessage()    {}

func (m *BuildingLevelUpMsgRes) GetBuilding() *common_msg.BuildingT {
	if m != nil {
		return m.Building
	}
	return nil
}

// //////////////////////////////////////////////
// 士兵,阵形
// //////////////////////////////////////////////
type UpdateLineupMsg struct {
	Lineup           *common_msg.UserLineupT `protobuf:"bytes,1,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateLineupMsg) Reset()         { *m = UpdateLineupMsg{} }
func (m *UpdateLineupMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateLineupMsg) ProtoMessage()    {}

func (m *UpdateLineupMsg) GetLineup() *common_msg.UserLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type UpdateLineupMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateLineupMsgRes) Reset()         { *m = UpdateLineupMsgRes{} }
func (m *UpdateLineupMsgRes) String() string { return proto.CompactTextString(m) }
func (*UpdateLineupMsgRes) ProtoMessage()    {}

type AddSoldierMsg struct {
	SoldierId        *uint32 `protobuf:"varint,1,opt,name=soldier_id" json:"soldier_id,omitempty"`
	SoldierCnt       *uint32 `protobuf:"varint,2,opt,name=soldier_cnt" json:"soldier_cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddSoldierMsg) Reset()         { *m = AddSoldierMsg{} }
func (m *AddSoldierMsg) String() string { return proto.CompactTextString(m) }
func (*AddSoldierMsg) ProtoMessage()    {}

func (m *AddSoldierMsg) GetSoldierId() uint32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *AddSoldierMsg) GetSoldierCnt() uint32 {
	if m != nil && m.SoldierCnt != nil {
		return *m.SoldierCnt
	}
	return 0
}

type AddSoldierMsgRes struct {
	SoldierId        *uint32 `protobuf:"varint,1,opt,name=soldier_id" json:"soldier_id,omitempty"`
	SoldierCnt       *uint32 `protobuf:"varint,2,opt,name=soldier_cnt" json:"soldier_cnt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddSoldierMsgRes) Reset()         { *m = AddSoldierMsgRes{} }
func (m *AddSoldierMsgRes) String() string { return proto.CompactTextString(m) }
func (*AddSoldierMsgRes) ProtoMessage()    {}

func (m *AddSoldierMsgRes) GetSoldierId() uint32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *AddSoldierMsgRes) GetSoldierCnt() uint32 {
	if m != nil && m.SoldierCnt != nil {
		return *m.SoldierCnt
	}
	return 0
}

type NotifySoldierMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifySoldierMsg) Reset()         { *m = NotifySoldierMsg{} }
func (m *NotifySoldierMsg) String() string { return proto.CompactTextString(m) }
func (*NotifySoldierMsg) ProtoMessage()    {}

type NotifySoldierMsgRes struct {
	Soldiers         []*common_msg.SoldierT `protobuf:"bytes,1,rep,name=soldiers" json:"soldiers,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *NotifySoldierMsgRes) Reset()         { *m = NotifySoldierMsgRes{} }
func (m *NotifySoldierMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifySoldierMsgRes) ProtoMessage()    {}

func (m *NotifySoldierMsgRes) GetSoldiers() []*common_msg.SoldierT {
	if m != nil {
		return m.Soldiers
	}
	return nil
}

type NotifyUpdateLineupMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyUpdateLineupMsg) Reset()         { *m = NotifyUpdateLineupMsg{} }
func (m *NotifyUpdateLineupMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyUpdateLineupMsg) ProtoMessage()    {}

type NotifyUpdateLineupMsgRes struct {
	Lineup           *common_msg.UserLineupT `protobuf:"bytes,1,opt,name=lineup" json:"lineup,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *NotifyUpdateLineupMsgRes) Reset()         { *m = NotifyUpdateLineupMsgRes{} }
func (m *NotifyUpdateLineupMsgRes) String() string { return proto.CompactTextString(m) }
func (*NotifyUpdateLineupMsgRes) ProtoMessage()    {}

func (m *NotifyUpdateLineupMsgRes) GetLineup() *common_msg.UserLineupT {
	if m != nil {
		return m.Lineup
	}
	return nil
}

type SoldierLevelUpMsg struct {
	SoldierId        *uint32 `protobuf:"varint,1,opt,name=soldier_id" json:"soldier_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SoldierLevelUpMsg) Reset()         { *m = SoldierLevelUpMsg{} }
func (m *SoldierLevelUpMsg) String() string { return proto.CompactTextString(m) }
func (*SoldierLevelUpMsg) ProtoMessage()    {}

func (m *SoldierLevelUpMsg) GetSoldierId() uint32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

type SoldierLevelUpMsgRes struct {
	SoldierId        *uint32 `protobuf:"varint,1,opt,name=soldier_id" json:"soldier_id,omitempty"`
	SoldierLevel     *uint32 `protobuf:"varint,2,opt,name=soldier_level" json:"soldier_level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SoldierLevelUpMsgRes) Reset()         { *m = SoldierLevelUpMsgRes{} }
func (m *SoldierLevelUpMsgRes) String() string { return proto.CompactTextString(m) }
func (*SoldierLevelUpMsgRes) ProtoMessage()    {}

func (m *SoldierLevelUpMsgRes) GetSoldierId() uint32 {
	if m != nil && m.SoldierId != nil {
		return *m.SoldierId
	}
	return 0
}

func (m *SoldierLevelUpMsgRes) GetSoldierLevel() uint32 {
	if m != nil && m.SoldierLevel != nil {
		return *m.SoldierLevel
	}
	return 0
}

// //////////////////////////////////////////////
// 系统
// //////////////////////////////////////////////
type SysInformationMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SysInformationMsg) Reset()         { *m = SysInformationMsg{} }
func (m *SysInformationMsg) String() string { return proto.CompactTextString(m) }
func (*SysInformationMsg) ProtoMessage()    {}

type SysInformationMsgRes struct {
	TimeSecond       *uint32 `protobuf:"varint,1,opt,name=time_second" json:"time_second,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SysInformationMsgRes) Reset()         { *m = SysInformationMsgRes{} }
func (m *SysInformationMsgRes) String() string { return proto.CompactTextString(m) }
func (*SysInformationMsgRes) ProtoMessage()    {}

func (m *SysInformationMsgRes) GetTimeSecond() uint32 {
	if m != nil && m.TimeSecond != nil {
		return *m.TimeSecond
	}
	return 0
}

type GmMsg struct {
	Msg              []string `protobuf:"bytes,1,rep,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GmMsg) Reset()         { *m = GmMsg{} }
func (m *GmMsg) String() string { return proto.CompactTextString(m) }
func (*GmMsg) ProtoMessage()    {}

func (m *GmMsg) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

type GmMsgRes struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GmMsgRes) Reset()         { *m = GmMsgRes{} }
func (m *GmMsgRes) String() string { return proto.CompactTextString(m) }
func (*GmMsgRes) ProtoMessage()    {}
